name: nabd_al_hayah
description: Nabd Al-Hayah - Your Personal Nutrition Companion
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_fonts: ^6.0.0
  percent_indicator: ^4.2.2
  fl_chart: ^0.65.0

  # ✅ Firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.6.0
  cloud_functions: ^4.6.0
  firebase_crashlytics: ^3.4.8

  # ✅ Health & Activity Tracking
  pedometer: ^4.0.2
  sensors_plus: ^4.0.2

  # ✅ Barcode Scanning & Camera
  mobile_scanner: ^3.5.7
  camera: ^0.10.5
  permission_handler: ^11.1.0
  google_mlkit_barcode_scanning: ^0.10.0

  # ✅ Additional utilities
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  http: ^1.1.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  geolocator: ^10.1.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # ✅ Add flutter_launcher_icons package

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# ✅ Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"   # place your 1024x1024 logo here
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
