// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANw3lESl8tjOKOpa1bnLONWBwUrzSw8rA',
    appId: '1:662403799759:web:43a02917b53022de0875ba',
    messagingSenderId: '662403799759',
    projectId: 'nabd-al-hayah',
    authDomain: 'nabd-al-hayah.firebaseapp.com',
    storageBucket: 'nabd-al-hayah.firebasestorage.app',
    measurementId: 'G-TV7VERB3F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj9I-snP24SkX7E8B5Xj5S007yCnWvqYE',
    appId: '1:662403799759:android:ba52723e378743320875ba',
    messagingSenderId: '662403799759',
    projectId: 'nabd-al-hayah',
    storageBucket: 'nabd-al-hayah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtN9dd6IZjs4qBWRstcN-55pXA3ggAB6c',
    appId: '1:662403799759:ios:4d3cc2ed531449190875ba',
    messagingSenderId: '662403799759',
    projectId: 'nabd-al-hayah',
    storageBucket: 'nabd-al-hayah.firebasestorage.app',
    iosClientId: '662403799759-m48p3psq9iajbnrfdpq6en47jdvf0cee.apps.googleusercontent.com',
    iosBundleId: 'com.sfd.nabdalhayah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANw3lESl8tjOKOpa1bnLONWBwUrzSw8rA',
    appId: '1:662403799759:web:4c03158f49466f910875ba',
    messagingSenderId: '662403799759',
    projectId: 'nabd-al-hayah',
    authDomain: 'nabd-al-hayah.firebaseapp.com',
    storageBucket: 'nabd-al-hayah.firebasestorage.app',
    measurementId: 'G-N0TDXYSBS8',
  );

}