import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'core/app_theme.dart';
import 'presentation/screens/login_screen.dart';
import 'presentation/navigation/main_navigation.dart';
import 'presentation/screens/splash_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const NabdAlHayahApp());
}

class NabdAlHayahApp extends StatelessWidget {
  const NabdAlHayahApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Nabd Al-Hayah',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      home: const RootScreen(), // ✅ Root screen decides where to go
    );
  }
}

class RootScreen extends StatelessWidget {
  const RootScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // Still loading → show splash
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const SplashScreen();
        }

        // User is logged in → go to main navigation
        if (snapshot.hasData) {
          return const MainNavigation();
        }

        // User not logged in → show login screen
        return const LoginScreen();
      },
    );
  }
}
