import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart'; // 🔥 Crashlytics
import 'package:provider/provider.dart'; // 🚀 Provider for state management
import 'firebase_options.dart'; // generated by flutterfire configure
import 'core/app_theme.dart';
import 'core/error_handler.dart'; // ⚠️ Error handling
import 'presentation/screens/start_page.dart';
import 'modules/auth/screens/login_screen.dart'; // 📁 New auth module structure
import 'modules/auth/providers/auth_provider.dart' as custom_auth; // 🚀 Auth provider
import 'modules/dashboard/providers/dashboard_provider.dart'; // 🚀 Dashboard provider
import 'modules/home/providers/home_provider.dart'; // 🚀 Home provider
import 'modules/activity/providers/activity_provider.dart'; // 🚀 Activity provider
import 'modules/food_logging/providers/food_logging_provider.dart'; // 🚀 Food Logging provider
import 'modules/profile/providers/profile_provider.dart'; // 🚀 Profile provider
import 'services/global_step_counter_provider.dart'; // 🚀 Global Step Counter provider
import 'presentation/navigation/main_navigation.dart';
import 'presentation/screens/splash_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // ⚠️ Initialize global error handling with Crashlytics
  ErrorHandler.initialize();
  
  // 🔥 Enable Crashlytics collection (set to false for debug builds if needed)
  FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(true);

  runApp(const NabdAlHayahApp());
}

class NabdAlHayahApp extends StatefulWidget {
  const NabdAlHayahApp({super.key});

  @override
  State<NabdAlHayahApp> createState() => _NabdAlHayahAppState();
}

class _NabdAlHayahAppState extends State<NabdAlHayahApp> {
  ThemeMode _themeMode = ThemeMode.system;

  @override
  void initState() {
    super.initState();
    _loadThemeMode();
  }

  Future<void> _loadThemeMode() async {
    final savedThemeMode = await AppTheme.getSavedThemeMode();
    setState(() {
      _themeMode = savedThemeMode;
    });
  }

  void updateThemeMode(ThemeMode themeMode) {
    setState(() {
      _themeMode = themeMode;
    });
    AppTheme.saveThemeMode(themeMode);
  }

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // 🚀 Auth Provider for global authentication state management
        ChangeNotifierProvider(
          create: (_) => custom_auth.AuthProvider(),
        ),
        // 🚀 Dashboard Provider for navigation state management
        ChangeNotifierProvider(
          create: (_) => DashboardProvider(),
        ),
        // 🚀 Home Provider for home screen state management
        ChangeNotifierProvider(
          create: (_) => HomeProvider(),
        ),
        // 🚀 Activity Provider for activity screen state management
        ChangeNotifierProvider(
          create: (_) => ActivityProvider(),
        ),
        // 🚀 Food Logging Provider for food logging screen state management
        ChangeNotifierProvider(
          create: (_) => FoodLoggingProvider(),
        ),
        // 🚀 Profile Provider for profile screen state management
        ChangeNotifierProvider(
          create: (_) => ProfileProvider(),
        ),
        // 🚀 Global Step Counter Provider for real-time step counting across all screens
        ChangeNotifierProvider(
          create: (_) => GlobalStepCounterProvider(),
        ),
        // Add more providers here as needed
      ],
      child: MaterialApp(
        title: 'Nabd Al-Hayah',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.lightTheme,
        // 🎨 Removed dark theme - using light theme only
        themeMode: ThemeMode.light, // Always use light theme
        home: ThemeModeProvider(
          updateThemeMode: updateThemeMode,
          child: const RootScreen(),
        ),
      ),
    );
  }
}

class RootScreen extends StatefulWidget {
  const RootScreen({super.key});

  @override
  State<RootScreen> createState() => _RootScreenState();
}

class _RootScreenState extends State<RootScreen> {
  bool _hasShownStartPage = false;

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // Still loading → show splash
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const SplashScreen();
        }

        // User is logged in → initialize step counter and go to main navigation
        if (snapshot.hasData) {
          return const MainNavigationWithStepCounter();
        }

        // User not logged in → show start page first, then login
        if (!_hasShownStartPage) {
          return const StartPage();
        }
        return const LoginScreen();
      },
    );
  }
}

/// ✅ Provider widget for theme mode changes
class ThemeModeProvider extends InheritedWidget {
  const ThemeModeProvider({
    super.key,
    required this.updateThemeMode,
    required Widget child,
  }) : super(child: child);

  final void Function(ThemeMode) updateThemeMode;

  static ThemeModeProvider? of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<ThemeModeProvider>();
  }

  @override
  bool updateShouldNotify(covariant ThemeModeProvider oldWidget) {
    return updateThemeMode != oldWidget.updateThemeMode;
  }
}

/// Wrapper widget that initializes global step counter before showing main navigation
class MainNavigationWithStepCounter extends StatefulWidget {
  const MainNavigationWithStepCounter({super.key});

  @override
  State<MainNavigationWithStepCounter> createState() => _MainNavigationWithStepCounterState();
}

class _MainNavigationWithStepCounterState extends State<MainNavigationWithStepCounter> {
  @override
  void initState() {
    super.initState();
    // Initialize global step counter when user is logged in
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _initializeGlobalStepCounter();
    });
  }

  Future<void> _initializeGlobalStepCounter() async {
    try {
      final globalStepCounter = context.read<GlobalStepCounterProvider>();
      await globalStepCounter.initialize();
      
      // Connect all providers to global step counter
      final homeProvider = context.read<HomeProvider>();
      homeProvider.setGlobalStepCounter(globalStepCounter);
      
      final dashboardProvider = context.read<DashboardProvider>();
      dashboardProvider.setGlobalStepCounter(globalStepCounter);
      
      final profileProvider = context.read<ProfileProvider>();
      profileProvider.setGlobalStepCounter(globalStepCounter);
      
      final activityProvider = context.read<ActivityProvider>();
      activityProvider.setGlobalStepCounter(globalStepCounter);
      
      debugPrint('Global step counter initialized and connected to all providers successfully');
    } catch (e) {
      debugPrint('Failed to initialize global step counter: $e');
      // Don't prevent app from working if step counter fails
    }
  }

  @override
  Widget build(BuildContext context) {
    return const MainNavigation();
  }
}
